---
# tasks file for kostyrevaa.openswan

- name: install package
  package:
    name: openswan
    state: present
  when: ansible_distribution != "Amazon"

- name: install system updates for amazon distros
  yum: name=openswan state=latest
  when: ansible_distribution == "Amazon"

- name: render template /etc/ipsec.conf
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: '0600'
  notify: restart ipsec service
  tags: config

- name: render /etc/ipsec.d/{{ item.key | regex_replace('%','') }}.conf
  template:
    src: conn.j2
    dest: "/etc/ipsec.d/{{ item.key | regex_replace('%','') }}.conf"
    owner: root
    group: root
    mode: '0600'
  with_dict: "{{ openswan_connections }}"
  notify: restart ipsec service
  tags:
    - config
    - conn

- name: make sure /etc/ipsec.secrets includes other secrets
  copy:
    content: "include ipsec.d/*.secrets\n"
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: '0600'

- name: render /etc/ipsec.d/{{ item.key }}.secrets
  template:
    src: secrets.j2
    dest: "/etc/ipsec.d/{{ item.key }}.secrets"
    owner: root
    group: root
    mode: '0600'
  with_dict: "{{ openswan_connections }}"
  when:
    - openswan_manage_secrets
    - item.value.psk is defined
  notify: restart ipsec service
  tags:
    - config
    - secrets

- name: Setup network for openswan
  shell: |
    echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
    echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
    echo 0 > /proc/sys/net/ipv4/conf/default/send_redirects
    echo 0 > /proc/sys/net/ipv4/conf/eth0/send_redirects
    echo 0 > /proc/sys/net/ipv4/conf/lo/send_redirects
    echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects
    echo 0 > /proc/sys/net/ipv4/conf/default/accept_redirects
    echo 0 > /proc/sys/net/ipv4/conf/eth0/accept_redirects
    echo 0 > /proc/sys/net/ipv4/conf/lo/accept_redirects

- name: Restart network
  service:
    name: network
    state: restarted

- name: enable and start ipsec service
  service:
    name: ipsec
    state: started
    enabled: yes
  when: openswan_manage_service
